name: Install Python and required modules
on: [push, pull_request]

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install python version
        with:
          default: 3.9.5 # pick 3.9.5 verion 
          command: pip install -U pip  # upgrade pip after installing python
      - name: Install dependencies
        run: pip install -r requirements.txt --upgrade pip
